### PR TITLE
Allow `maintain` permission for publishing on v1

### PR DESCRIPTION
**Pull request by AlexV525**
Fixes https://github.com/cfug/dio/actions/runs/5169294477/jobs/9311455329 by @ueman from https://github.com/cfug/dio/issues/1633#issuecomment-1575564843.

### CODE REVIEW

**Review by CaiJingLong — COMMENTED** [review]
image

The permission like this:

```json
"permissions": {
  "admin": false,
  "maintain": true,
   "push": true,
   "triage": true,
   "pull": true
}
```

So, I think need replace 'write' to 'push'.

**Comment by AlexV525** [comment]
AFAIK the v1 only read from the "permission" key, correct? What's the point of the previous comment?

**Comment by AlexV525** [comment]
> So, I think need replace 'write' to 'push'.

Then `const writable = permissionLevel.data.permissions.push`?

**Comment by CaiJingLong** [comment]
I think, use the permissions maybe a good idea.

**Comment by ueman** [comment]
There's still something wrong with publishing.

**Comment by AlexV525** [comment]
Let's migrate to v2 instead.

**Pull request merged**
